name: app_agachaditos
description: Aplication about the bussiness agachaditos

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  auto_size_text: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  salomon_bottom_bar: ^3.3.2
  google_sign_in: ^6.1.5
  firebase_auth: ^4.11.0
  firebase_core: ^2.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dio: ^5.3.3


flutter:
  uses-material-design: true
